before_script:
    # Install dependencies
    - bash build/docker_install.sh > /dev/null
    # Install composer dependencies
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    # Move redis test config file into place
    - mv "./tests/redis.toml" "./app/config/redis.toml"

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

services:
    - redis:latest

test:5.6:
    image: php:5.6
    script:
      - phpunit -c build

test:7:
    image: php:7
    script:
      - phpunit -c build