before_script:
    # Install dependencies
    - bash build/docker_install.sh > /dev/null

services:
    - redis:latest

test:5.5:
    image: php:5.5
    script:
      - phpunit -c build

test:5.6:
    image: php:5.6
    script:
      - phpunit -c build

test:7:
    image: php:7
    script:
      - phpunit -c build