language: php

install:
  - composer install --ignore-platform-reqs

php:
  - 8.0
  - 8.1
  - nightly

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c build

#matrix:
#  allow_failures:
#    - php: nightly
