language: php

install:
  - composer install

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly


before_script:
  - phpenv config-add .travis.ini

script:
  - mkdir -p build/logs
  - phpunit -c build

services:
  - redis

after_script:
    - CODECLIMATE_REPO_TOKEN=2cbddcebcb9256b3402867282e119dbe61de0b31039325356af3c7d72ed6d058 vendor/bin/test-reporter

matrix:
  allow_failures:
    - php: 5.5
    - php: nightly
    - php: hhvm

addons:
    code_climate:
        repo_token: 2cbddcebcb9256b3402867282e119dbe61de0b31039325356af3c7d72ed6d058