language: php

install:
  - composer install --ignore-platform-reqs

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

script:
  - mkdir -p build/logs
  - vendor/bin/robo lint
  - phpdbg -qrr -- vendor/bin/phpunit -c build

after_script:
    - CODECLIMATE_REPO_TOKEN=2cbddcebcb9256b3402867282e119dbe61de0b31039325356af3c7d72ed6d058 vendor/bin/test-reporter

matrix:
  allow_failures:
    - php: nightly

addons:
    code_climate:
        repo_token: 2cbddcebcb9256b3402867282e119dbe61de0b31039325356af3c7d72ed6d058