language: php

install:
  - composer install

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

script:
  - mkdir -p build/logs
  - phpunit -c build

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover

matrix:
  allow_failures:
    - php: nightly

addons:
    code_climate:
        repo_token: 2cbddcebcb9256b3402867282e119dbe61de0b31039325356af3c7d72ed6d058