#!/usr/bin/env php
<?php declare(strict_types=1);

// Set up autoloader for third-party dependencies
require_once __DIR__ . '/vendor/autoload.php';

use Aviat\AnimeClient\Command;

$_SERVER['HTTP_HOST'] = 'localhost';

// -----------------------------------------------------------------------------
// Start console script
// -----------------------------------------------------------------------------
try
{
	(new \ConsoleKit\Console([
		'cache:clear' => Command\CacheClear::class,
		'cache:prime' => Command\CachePrime::class,
		'lists:sync' => Command\SyncKitsuWithMal::class,
		'cache-prime' => Command\CachePrime::class,
		'cache-clear' => Command\CacheClear::class,
		'clear-cache' => Command\CacheClear::class,
		'sync-lists' => Command\SyncKitsuWithMal::class,
	]))->run();
}
catch (\Exception $e)
{

}

