[anime_list]
	route_prefix = "/anime"
	[anime_list.items]
		watching = '/watching'
		plan_to_watch = '/plan_to_watch'
		on_hold = '/on_hold'
		dropped = '/dropped'
		completed = '/completed'
		all = '/all'

[manga_list]
	route_prefix = "/manga"
	[manga_list.items]
		reading = '/reading'
		plan_to_read = '/plan_to_read'
		on_hold = '/on_hold'
		dropped = '/dropped'
		completed = '/completed'
		all = '/all'